// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrnHdR1FJhWHIza6OZpmkSD4B4rJy5O_g',
    appId: '1:262666226794:web:99117f6a67e46902c34e13',
    messagingSenderId: '262666226794',
    projectId: 'mi-recetario-app',
    authDomain: 'mi-recetario-app.firebaseapp.com',
    storageBucket: 'mi-recetario-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-nD0q-RHEVVE7-8pWzsLhzNX50I2L48',
    appId: '1:262666226794:android:d4a60225d8142402c34e13',
    messagingSenderId: '262666226794',
    projectId: 'mi-recetario-app',
    storageBucket: 'mi-recetario-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ZTjTq5LibJFpbm-2aGm2ptelbOFQBSg',
    appId: '1:262666226794:ios:856a9e957839efc9c34e13',
    messagingSenderId: '262666226794',
    projectId: 'mi-recetario-app',
    storageBucket: 'mi-recetario-app.firebasestorage.app',
    iosBundleId: 'com.example.miRecetarioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ZTjTq5LibJFpbm-2aGm2ptelbOFQBSg',
    appId: '1:262666226794:ios:856a9e957839efc9c34e13',
    messagingSenderId: '262666226794',
    projectId: 'mi-recetario-app',
    storageBucket: 'mi-recetario-app.firebasestorage.app',
    iosBundleId: 'com.example.miRecetarioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrnHdR1FJhWHIza6OZpmkSD4B4rJy5O_g',
    appId: '1:262666226794:web:33ac470911345933c34e13',
    messagingSenderId: '262666226794',
    projectId: 'mi-recetario-app',
    authDomain: 'mi-recetario-app.firebaseapp.com',
    storageBucket: 'mi-recetario-app.firebasestorage.app',
  );

}